apiVersion: apps/v1
kind: "Deployment"
metadata:
  labels:
    provider: "fabric8"
  name: "zipkin"
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: "fabric8"
      group: "io.fabric8.zipkin"
  template:
    metadata:
      labels:
        provider: "fabric8"
        group: "io.fabric8.zipkin"
    spec:
      containers:
      - env:
        - name: "STORAGE_PORT_9042_TCP_ADDR"
          value: "zipkin-cassandra:9411"
        - name: "STORAGE_PORT_3306_TCP_ADDR"
          value: "zipkin-mysql:3306"
        - name: "STORAGE_TYPE"
          value: "mysql"
        - name: "TRANSPORT_TYPE"
          value: "http"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "openzipkin/zipkin:${zipkin.version}"
        name: "zipkin"
        readinessProbe:
          httpGet:
            path: "/api/v1/services"
            port: 9411
          initialDelaySeconds: 5
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path:   /prometheus
    prometheus.io/port:   '9411'
    fabric8.io/app-menu: management
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.zipkin"
  name: "zipkin"
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 9411
  selector:
    project: "zipkin"
    provider: "fabric8"
    group: "io.fabric8.zipkin"
  type: "LoadBalancer"