apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: sourav40/payment-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 10
          periodSeconds: 3
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 130
          timeoutSeconds: 2
          periodSeconds: 8
          failureThreshold: 1
        env:
        - name: APP_PROFILE
          valueFrom:
            configMapKeyRef:
              name: app
              key: APP_PROFILE
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: app
              key: MYSQL_DATABASE_URL
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: app
              key: MYSQL_DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: app
              key: BOOKING_DATABASE_NAME
        - name: DATABSE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysqldb
              key: MYSQL_DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqldb
              key: MYSQL_DATABASE_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app
              key: JWT_SECRET
        - name: JWT_PREFIX
          valueFrom:
            secretKeyRef:
              name: app
              key: JWT_PREFIX
        - name: CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: app
              key: CONSUL_HOST
        - name: CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: app
              key: CONSUL_PORT
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: app
              key: KAFKA_URL
        - name: KAFKA_PORT
          valueFrom:
            configMapKeyRef:
              name: app
              key: KAFKA_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
    spring-boot: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: payment-service
  type: ClusterIP